directories:
  output: dist
  buildResources: assets
files:
  - filter:
      - build/**/*
      - build/**/*
      - node_modules/**/*
extraMetadata:
  main: build/Main.js
appId: nonExistentID
extends: react-cra
electronVersion: 4.0.1
